export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_HEAT_MAP_DATA = 'GET_HEAT_MAP_DATA';

/** Constant for tours api */ 
export const LOAD_TOURS_SUCCESS = 'LOAD_TOURS_SUCCESS';
export const LOAD_TOUR_SUCCESS = 'LOAD_TOUR_SUCCESS';
export const UPDATE_TOUR_SUCCESS = 'UPDATE_TOUR_SUCCESS';
export const CREATE_TOUR_SUCCESS = 'CREATE_TOUR_SUCCESS';
export const DELETE_TOUR_SUCCESS = 'DELETE_TOUR_SUCCESS';
export const TOUR_MAP_SUCCESS = 'TOUR_MAP_SUCCESS';
export const TOUR_STOPS_SUCCESS = 'TOUR_STOPS_SUCCESS';

/** Constant for apps api */ 
export const LOAD_APPS_SUCCESS = 'LOAD_APPS_SUCCESS';
export const LOAD_APP_SUCCESS = 'LOAD_APP_SUCCESS';
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS';
export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS';
export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';
export const LOAD_LANGUAGES_SUCCESS = 'LOAD_LANGUAGES_SUCCESS';
export const LOAD_APPS_USERS = 'LOAD_APPS_USERS';
export const LOAD_SOCIAL_TYPES_SUCCESS = 'LOAD_SOCIAL_TYPES_SUCCESS';
export const LOAD_APPS_TYPES_SUCCESS = 'LOAD_APPS_TYPES_SUCCESS';
export const APP_MORE_SUCCESS = 'APP_MORE_SUCCESS';

/** Constant for content api */
export const LOAD_CONTENTS_SUCCESS = 'LOAD_CONTENTS_SUCCESS';

/** Constant for Analytics api */
export const LOAD_SALES_SUCCESS = 'LOAD_SALES_SUCCESS';
export const LOAD_ENGAGEMENTS_SUCCESS = 'LOAD_ENGAGEMENTS_SUCCESS';
export const LOAD_DOWNLOAD_SUCCESS = 'LOAD_DOWNLOAD_SUCCESS';


/** Constant for Dashboards api */
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const LOAD_LATEST_INTERACTION_SUCCESS = 'LOAD_LATEST_INTERACTION_SUCCESS';

/** Constant for Billing api */
export const LOAD_BILLING_SUCCESS = 'LOAD_BILLING_SUCCESS';
export const LOAD_BILLING_DETAIL_SUCCESS = 'LOAD_BILLING_DETAIL_SUCCESS';

/** Constant for Screens api */
export const LOAD_SCREENS_SUCCESS = 'LOAD_SCREENS_SUCCESS';
export const LOAD_APPSCREENS_SUCCESS = 'LOAD_APPSCREENS_SUCCESS';
